---
apiVersion: v1
kind: Service
metadata:
  name: wikijs
  labels:
    app: wikijs
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: LoadBalancer
  selector:
    app: wikijs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
      - name: wikijs
        image: requarks/wiki:beta
        imagePullPolicy: "IfNotPresent"
        env:
        - name: DB_TYPE
          value: postgres 
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: wiki
        - name: DB_USER
          value: wikiUser
        - name: DB_PORT
          value: "5432"
        - name: DB_PASS
          value: "54321"
        ports:
        - containerPort: 3000