apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.16.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
-- 
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 7.16.2
  count: 1
  elasticsearchRef:
    name: quickstar