- hosts: localhost
  tasks: 
  - name: Instalação da BD
    command: sudo kubectl apply -f postgre-pv.yaml
  - name: Deployment da BD
    command: sudo kubectl apply -f postgres-deployment.yaml
  - name: Deployment Wikijs
    command: sudo kubectl apply -f wikijs-deployment.yaml